name: herometrics
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/portraits/
    - assets/images/skills/
    - assets/icons/

    - assets/images/skills/tanks/dva/
    - assets/images/skills/tanks/doomfist/
    - assets/images/skills/tanks/junkerqueen/
    - assets/images/skills/tanks/mauga/
    - assets/images/skills/tanks/orisa/
    - assets/images/skills/tanks/ramattra/
    - assets/images/skills/tanks/reinhardt/
    - assets/images/skills/tanks/roadhog/
    - assets/images/skills/tanks/sigma/
    - assets/images/skills/tanks/winston/
    - assets/images/skills/tanks/wreckingball/
    - assets/images/skills/tanks/zarya/

    - assets/images/skills/dps/ashe/
    - assets/images/skills/dps/bastion/
    - assets/images/skills/dps/cassidy/
    - assets/images/skills/dps/echo/
    - assets/images/skills/dps/genji/
    - assets/images/skills/dps/hanzo/
    - assets/images/skills/dps/junkrat/
    - assets/images/skills/dps/mei/
    - assets/images/skills/dps/pharah/
    - assets/images/skills/dps/reaper/
    - assets/images/skills/dps/sojourn/
    - assets/images/skills/dps/soldier76/
    - assets/images/skills/dps/sombra/
    - assets/images/skills/dps/symmetra/
    - assets/images/skills/dps/torbjörn/
    - assets/images/skills/dps/tracer/
    - assets/images/skills/dps/venture/
    - assets/images/skills/dps/widowmaker/

    - assets/images/skills/supports/ana/
    - assets/images/skills/supports/baptiste/
    - assets/images/skills/supports/brigitte/
    - assets/images/skills/supports/illari/
    - assets/images/skills/supports/kiriko/
    - assets/images/skills/supports/lifeweaver/
    - assets/images/skills/supports/lúcio/
    - assets/images/skills/supports/mercy/
    - assets/images/skills/supports/moira/
    - assets/images/skills/supports/zenyatta/

    # dps assets data  
    - lib/data/dps/ashe.json
    - lib/data/dps/bastion.json
    - lib/data/dps/cassidy.json
    - lib/data/dps/echo.json
    - lib/data/dps/genji.json
    - lib/data/dps/hanzo.json
    - lib/data/dps/junkrat.json
    - lib/data/dps/mei.json
    - lib/data/dps/pharah.json
    - lib/data/dps/reaper.json
    - lib/data/dps/sojourn.json
    - lib/data/dps/soldier76.json
    - lib/data/dps/sombra.json
    - lib/data/dps/symmetra.json
    - lib/data/dps/torbjörn.json
    - lib/data/dps/tracer.json
    - lib/data/dps/venture.json
    - lib/data/dps/widowmaker.json

    # supports assets data  
    - lib/data/supports/ana.json
    - lib/data/supports/baptiste.json
    - lib/data/supports/brigitte.json
    - lib/data/supports/illari.json
    - lib/data/supports/kiriko.json
    - lib/data/supports/lifeweaver.json
    - lib/data/supports/lúcio.json
    - lib/data/supports/mercy.json
    - lib/data/supports/moira.json
    - lib/data/supports/zenyatta.json

    # tanks assets data  
    - lib/data/tanks/dva.json
    - lib/data/tanks/doomfist.json
    - lib/data/tanks/junkerqueen.json
    - lib/data/tanks/mauga.json
    - lib/data/tanks/orisa.json
    - lib/data/tanks/ramattra.json
    - lib/data/tanks/reinhardt.json
    - lib/data/tanks/roadhog.json
    - lib/data/tanks/sigma.json
    - lib/data/tanks/winston.json
    - lib/data/tanks/wreckingball.json
    - lib/data/tanks/zarya.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
